import type { Metadata } from "next";
import {  Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSerifBengli = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${notoSerifBengli.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        {children}
        </body>
    </html>
  );
}
